import Head from "next/head";
import {
  Flex,
  Text,
  Stack,
  Box,
  Button,
  Table,
  Tbody,
  Th,
  Thead,
  Tr,
  TableContainer,
} from "@chakra-ui/react";
import { Header } from "../components/Header";
import { AddIcon } from "@chakra-ui/icons";
import {ModalAdd} from "../components/ModalAdd"
import {ModalEdit} from "../components/ModalEdit"

export default function Home() {
  return (
    <>
      <Head>
        <title>Createe Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack
        mt={10}
        mx="auto"
        w={['100vw',490,700,900,1100]}
        maxW={1100}
        bg="#1c1458"
        direction="column"
      >
        <Header />
        <Flex justify="end" w="100%">
          
          <Button
            mr={5}
            leftIcon={<AddIcon />}
            colorScheme="linkedin"
            variant="outline"
            w="239px"
            mt={100}
         
          >
            Adicionar Colaborador
          </Button>
        </Flex>
        <Box>
        <Text fontSize="xl" color="#ffffff" ml={30}>Colaboradores:</Text>
        </Box>
        <Box overflowY="auto">
          <TableContainer bg="white" w={855} mx="auto" mb={10} borderRadius={5}>
            <Table variant="simple" >
              <Thead>
                <Tr textAlign="center" fontWeight="bold">
                  <Th color="#008cc9" textAlign="center">Foto</Th>
                  <Th color="#008cc9" textAlign="center">Nome</Th>
                  <Th color="#008cc9" textAlign="center">Email</Th>
                  <Th color="#008cc9" textAlign="center">Cargo</Th>
                  <Th color="#008cc9" textAlign="center">Salário</Th>
                  <Th color="#008cc9" textAlign="center">Editar</Th>
                </Tr>
              </Thead>
              <Tbody>      
              </Tbody>
            </Table>
          </TableContainer>
        </Box>
      </Stack>
      <ModalAdd/>
      <ModalEdit/>
    </>
  );
}
